redis-cluster:
  enabled: false
postgresql:
  enabled: true
postgresql-ha:
  enabled: false

persistence:
  enabled: true
# Enable ssh

service:
  http:
    type: ClusterIP
    port: 3000
    annotations:
      app: gitea
  ssh:
    annotations:
      metallb.universe.tf/allow-shared-ip: gite # This annotation is required for ssh to work with metallb
      # Honestly, I havent managed to get ssh working yet, so this may as well be useless :D

gitea:
  config:
    database:
      DB_TYPE: postgres
    session:
      PROVIDER: db
    cache:
      ADAPTER: memory
    queue:
      TYPE: level
    indexer:
      ISSUE_INDEXER_TYPE: bleve
      REPO_INDEXER_ENABLED: true
