apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ssl-cert-staging
  namespace: argocd
spec:
  secretName: vault-tls-stage
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  commonName: vault.ithankube.xyz
  dnsNames:
    - vault.ithankube.xyz
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
    group: cert-manager.io
