apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ssl-cert-production
  namespace: vault
spec:
  secretName: vault-tls-production
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: vault.ithankube.xyz
  dnsNames:
  - vault.ithankube.xyz