# server:
#   resources:
#     requests:
#       cpu: 100m
#       memory: 256Mi
#     limits:
#       cpu: 500m
#       memory: 512Mi
#   ha:
#     enabled: true
#     replicas: 1

# ui:
#   enabled: true
#   serviceType: "LoadBalancer"
#   serviceNodePort: null
#   externalPort: 8200
